name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry==1.8.4
          poetry config virtualenvs.create false
          poetry install --no-cache

      - name: Run flake8
        run: |
          flake8

      - name: Run tests
        run: |
          pytest
